# Создайте файл .database.ini из копии этого файла и замените значения переменных реальными данными

[postgresql]
host=хост
user=имя пользователя базы данных
password=пароль пользователя базы данных
port=порт